"""Data models for events and reminders."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Event:
    """A normalized event from any data source."""

    event_id: str
    title: str
    start: datetime
    end: datetime
    location: str = ""
    description: str = ""
    source: str = ""  # e.g. "google_calendar", "canvas", "zoom"
    raw: dict = field(default_factory=dict)

    def is_zoom(self) -> bool:
        """Check if this is a Zoom meeting."""
        indicators = ["zoom.us", "zoom meeting"]
        text = f"{self.location} {self.description} {self.title}".lower()
        return any(ind in text for ind in indicators)

    def has_physical_location(self) -> bool:
        """Check if this event has a physical address (not a URL)."""
        if not self.location:
            return False
        return not self.location.startswith(("http://", "https://"))

    def is_early_morning(self) -> bool:
        """Check if event starts before 9 AM."""
        return self.start.hour < 9


@dataclass
class Reminder:
    """A reminder generated by the AI agent."""

    event_id: str
    event_title: str
    remind_at: datetime
    message: str
    priority: str = "normal"  # "high", "normal", "low"
    channels: list[str] = field(default_factory=lambda: ["console"])


@dataclass
class Conflict:
    """A scheduling conflict detected by the AI agent."""

    event_ids: list[str]
    description: str
